# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshush < Formula
  desc "Interactive TUI for SSH keys, the agent, and ~/.ssh/config"
  homepage "https://github.com/s-johri/sshush"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/s-johri/sshush/releases/download/v0.7.0/sshush_darwin_amd64.tar.gz"
      sha256 "020121c42278657ec89e41cb260f83f56441696dfc123a5c49e734a4b2b3a917"

      define_method(:install) do
        bin.install "sshush"
        bash_completion.install "completions/sshush.bash" => "sshush"
        zsh_completion.install "completions/sshush.zsh" => "_sshush"
        fish_completion.install "completions/sshush.fish"
        man1.install "sshush.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/s-johri/sshush/releases/download/v0.7.0/sshush_darwin_arm64.tar.gz"
      sha256 "3d522d714847dddfc515b39dc03fe603e6184d09e12b706a150d6690a3a163a3"

      define_method(:install) do
        bin.install "sshush"
        bash_completion.install "completions/sshush.bash" => "sshush"
        zsh_completion.install "completions/sshush.zsh" => "_sshush"
        fish_completion.install "completions/sshush.fish"
        man1.install "sshush.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/s-johri/sshush/releases/download/v0.7.0/sshush_linux_amd64.tar.gz"
      sha256 "7497d33d48d74cf4a8a0004298441337be7c2fe5fbfc290459e84fe55ef4bbaa"
      define_method(:install) do
        bin.install "sshush"
        bash_completion.install "completions/sshush.bash" => "sshush"
        zsh_completion.install "completions/sshush.zsh" => "_sshush"
        fish_completion.install "completions/sshush.fish"
        man1.install "sshush.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/s-johri/sshush/releases/download/v0.7.0/sshush_linux_arm64.tar.gz"
      sha256 "a6d139474333742b1a90f5ef6e8243c45db52eb429503c8242a8dae4742d4a7f"
      define_method(:install) do
        bin.install "sshush"
        bash_completion.install "completions/sshush.bash" => "sshush"
        zsh_completion.install "completions/sshush.zsh" => "_sshush"
        fish_completion.install "completions/sshush.fish"
        man1.install "sshush.1"
      end
    end
  end

  test do
    system "#{bin}/sshush", "version"
  end
end
