# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshush < Formula
  desc "Interactive TUI for SSH keys, the agent, and ~/.ssh/config"
  homepage "https://github.com/s-johri/sshush"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/s-johri/sshush/releases/download/v0.9.0/sshush_darwin_amd64.tar.gz"
      sha256 "fcfe82b4831e7430546a295150177bc38a14f6b0094db08ec03c516b1725f7d1"

      define_method(:install) do
        bin.install "sshush"
        bash_completion.install "completions/sshush.bash" => "sshush"
        zsh_completion.install "completions/sshush.zsh" => "_sshush"
        fish_completion.install "completions/sshush.fish"
        man1.install "sshush.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/s-johri/sshush/releases/download/v0.9.0/sshush_darwin_arm64.tar.gz"
      sha256 "14581f0d70277679139cc979ba1435b3a4b41cc24d0e24d89c63aca8d526ed6e"

      define_method(:install) do
        bin.install "sshush"
        bash_completion.install "completions/sshush.bash" => "sshush"
        zsh_completion.install "completions/sshush.zsh" => "_sshush"
        fish_completion.install "completions/sshush.fish"
        man1.install "sshush.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/s-johri/sshush/releases/download/v0.9.0/sshush_linux_amd64.tar.gz"
      sha256 "21cd0ed1462e4b4ce135948bfefed45c40054b0a4076a36d5e034fa0dd3bcb0f"
      define_method(:install) do
        bin.install "sshush"
        bash_completion.install "completions/sshush.bash" => "sshush"
        zsh_completion.install "completions/sshush.zsh" => "_sshush"
        fish_completion.install "completions/sshush.fish"
        man1.install "sshush.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/s-johri/sshush/releases/download/v0.9.0/sshush_linux_arm64.tar.gz"
      sha256 "5721a50d00c779c979f705a1eebb13a3fde333975cd25daea1c859f043574dc8"
      define_method(:install) do
        bin.install "sshush"
        bash_completion.install "completions/sshush.bash" => "sshush"
        zsh_completion.install "completions/sshush.zsh" => "_sshush"
        fish_completion.install "completions/sshush.fish"
        man1.install "sshush.1"
      end
    end
  end

  test do
    system "#{bin}/sshush", "version"
  end
end
