# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshush < Formula
  desc "Interactive TUI for SSH keys, the agent, and ~/.ssh/config"
  homepage "https://github.com/s-johri/sshush"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/s-johri/sshush/releases/download/v0.10.0/sshush_darwin_amd64.tar.gz"
      sha256 "d7915421990d54c21b7cadb7bbae28a1559d7b64ef4d6166091d9d0f907ffad3"

      define_method(:install) do
        bin.install "sshush"
        bash_completion.install "completions/sshush.bash" => "sshush"
        zsh_completion.install "completions/sshush.zsh" => "_sshush"
        fish_completion.install "completions/sshush.fish"
        man1.install "sshush.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/s-johri/sshush/releases/download/v0.10.0/sshush_darwin_arm64.tar.gz"
      sha256 "a019e130975b20dc21355397cbb5595519f4e23e55ca5a3a2ac0bacfbd6309c2"

      define_method(:install) do
        bin.install "sshush"
        bash_completion.install "completions/sshush.bash" => "sshush"
        zsh_completion.install "completions/sshush.zsh" => "_sshush"
        fish_completion.install "completions/sshush.fish"
        man1.install "sshush.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/s-johri/sshush/releases/download/v0.10.0/sshush_linux_amd64.tar.gz"
      sha256 "a3764520848504a031e1dca4ef903513039270345e39780e35eb393cbec38547"
      define_method(:install) do
        bin.install "sshush"
        bash_completion.install "completions/sshush.bash" => "sshush"
        zsh_completion.install "completions/sshush.zsh" => "_sshush"
        fish_completion.install "completions/sshush.fish"
        man1.install "sshush.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/s-johri/sshush/releases/download/v0.10.0/sshush_linux_arm64.tar.gz"
      sha256 "ebdeaaa46a6bc03b0525706510a79fdb4947c19515a9348d63edc8328ae26063"
      define_method(:install) do
        bin.install "sshush"
        bash_completion.install "completions/sshush.bash" => "sshush"
        zsh_completion.install "completions/sshush.zsh" => "_sshush"
        fish_completion.install "completions/sshush.fish"
        man1.install "sshush.1"
      end
    end
  end

  test do
    system "#{bin}/sshush", "version"
  end
end
